export const OPS_ROLES = [
  'ADMIN', 'LEADERSHIP', 'OPS_MANAGER', 'BRANCH_MANAGER', 'CLAIMS_MANAGER',
  'SALES_MANAGER', 'FLEET_MANAGER', 'FINANCE_MANAGER', 'RECOVERY_MANAGER',
  'CLAIMS_TEAM_IN', 'CLAIMS_TEAM_OUT', 'CLAIMS_TEAM_LIABILITY', 'SALES_REP',
  'FLEET_COORDINATOR',
] as const;

export const ALL_STAFF = [...OPS_ROLES, 'CSE_DRIVER', 'RECOVERY_AGENT'] as const;

export const CLAIMS_ROLES = [
  'ADMIN', 'LEADERSHIP', 'OPS_MANAGER', 'BRANCH_MANAGER', 'CLAIMS_MANAGER',
  'CLAIMS_TEAM_IN', 'CLAIMS_TEAM_OUT', 'CLAIMS_TEAM_LIABILITY', 'RECOVERY_MANAGER',
] as const;

export const FINANCE_ROLES = [
  'ADMIN', 'LEADERSHIP', 'FINANCE_MANAGER', 'OPS_MANAGER', 'BRANCH_MANAGER',
] as const;
