ALTER TABLE "Branch" ALTER COLUMN "code" TYPE TEXT USING "code"::TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "suburb" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "postcode" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Branch" ALTER COLUMN "phone" DROP NOT NULL;
